### ISSUE TITLE
Bash one liner

### ISSUE THREAD

**Issue by samrocketman** [GunnJerkens/desavouer#1]
Coming from a system administrator's background this is how I would have approached the problem. Assuming it is a flat text file here's a bash one liner.

``` bash
cat backlinks.txt.sample | cut -d/ -f3 | sort -u | awk '{ print "domain:" $1}'
```

The `cat` command can combine one or more files with concatenation. If you want to write that to a file which can be submitted you just redirect the output.

``` bash
cat backlinks.txt.sample | cut -d/ -f3 | sort -u | awk '{ print "domain:" $1}' > output.txt
```

That could be converted into a script for regular use and inclusion into more advanced one liners.

**Comment by samrocketman** [comment]
Also, another way to turn it into a bash script so that it could be included into one liners.  `desavour.sh` follows.

``` bash
#!/bin/bash
#Created by Sam Gleske (github samrocketman)
#DESCRIPTION
#  Generates desavow file from a flat text file or reading input from stdin.
#  Script assumes you provide URLs one per line.
#  Script assumes you don't have spaces in your file name arguments.
#USAGE
#  desavour.sh backlinks.txt.sample
#  cat backlinks.txt.sample | desavour.sh
if [ "$#" -gt 0 ];do
  cat $@ | cut -d/ -f3 | sort -u | awk '{ print "domain:" $1}'
else
  #no arguments have been passed so read from stdin
  while read line; do
    echo "$line" | cut -d/ -f3 | awk '{ print "domain:" $1}'
  done | sort -u
fi
```

It can be used like...

``` bash
desavour.sh backlinks.txt.sample
cat backlinks.txt.sample | desavour.sh
desavour.sh < backlinks.txt.sample
```

This way it can be reused in one liners.

**Comment by shampine** [comment]
+1 that's an awesome shorthand solution. I dig it, thanks for taking the time.

**Comment by samrocketman** [comment]
@shampine neat blog btw.  I've been reading around and checking out your projects.

**Comment by shampine** [comment]
Appreciate it, I had dug through your repos maybe 6-8 months ago when I stumbled onto gitlab mirrors. Really impressed at your scripting.

**Comment by samrocketman** [comment]
It's a fun hobby of mine :)
